name: Test Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Runner
        shell: cmd
        run: |
          echo Runner is Working
          hostname
          dir

      - name: Show Date
        shell: cmd
        run: date /t && time /t
